# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/mblaze_test/mblaze_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test || ORIG_REF_NAME==mblaze_test} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_microblaze_0_1/mblaze_test_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_microblaze_0_1 || ORIG_REF_NAME==mblaze_test_microblaze_0_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_dlmb_v10_1/mblaze_test_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_dlmb_v10_1 || ORIG_REF_NAME==mblaze_test_dlmb_v10_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_ilmb_v10_1/mblaze_test_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_ilmb_v10_1 || ORIG_REF_NAME==mblaze_test_ilmb_v10_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_dlmb_bram_if_cntlr_1/mblaze_test_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mblaze_test_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_ilmb_bram_if_cntlr_1/mblaze_test_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mblaze_test_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_lmb_bram_1/mblaze_test_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_lmb_bram_1 || ORIG_REF_NAME==mblaze_test_lmb_bram_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_microblaze_0_axi_periph_1/mblaze_test_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mblaze_test_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_microblaze_0_axi_intc_1/mblaze_test_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mblaze_test_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_microblaze_0_xlconcat_1/mblaze_test_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_microblaze_0_xlconcat_1 || ORIG_REF_NAME==mblaze_test_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_mdm_1_1/mblaze_test_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_mdm_1_1 || ORIG_REF_NAME==mblaze_test_mdm_1_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_clk_wiz_1_1/mblaze_test_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_clk_wiz_1_1 || ORIG_REF_NAME==mblaze_test_clk_wiz_1_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_rst_clk_wiz_1_100M_1/mblaze_test_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mblaze_test_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_mig_7series_0_0/mblaze_test_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_mig_7series_0_0 || ORIG_REF_NAME==mblaze_test_mig_7series_0_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_mii_to_rmii_0_0/mblaze_test_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_mii_to_rmii_0_0 || ORIG_REF_NAME==mblaze_test_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_axi_uartlite_0_0/mblaze_test_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_axi_ethernetlite_0_0/mblaze_test_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_axi_ethernetlite_0_0 || ORIG_REF_NAME==mblaze_test_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_axi_timer_0_0/mblaze_test_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_axi_timer_0_0 || ORIG_REF_NAME==mblaze_test_axi_timer_0_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_xbar_0/mblaze_test_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_xbar_0 || ORIG_REF_NAME==mblaze_test_xbar_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_axi_smc_0/mblaze_test_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_axi_smc_0 || ORIG_REF_NAME==mblaze_test_axi_smc_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_rst_mig_7series_0_81M_0/mblaze_test_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==mblaze_test_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_rst_clk_wiz_1_50M_0/mblaze_test_rst_clk_wiz_1_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_rst_clk_wiz_1_50M_0 || ORIG_REF_NAME==mblaze_test_rst_clk_wiz_1_50M_0} -quiet] -quiet

# IP: bd/mblaze_test/ip/mblaze_test_auto_cc_0/mblaze_test_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_test_auto_cc_0 || ORIG_REF_NAME==mblaze_test_auto_cc_0} -quiet] -quiet

# XDC: bd/mblaze_test/mblaze_test_ooc.xdc
