// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test3\test3.v
// Created: 2021-01-04 19:17:43
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: test3
// Source Path: test3
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module test3
          (data1,
           temp_state1);


  input   [7:0] data1;  // uint8
  output  [7:0] temp_state1;  // uint8


  wire [7:0] sbox_val;  // uint8


  getSBoxValue u_getSBoxValue (.number(data1),  // uint8
                               .sbox_val(sbox_val)  // uint8
                               );

  assign temp_state1 = sbox_val;

endmodule  // test3

