// File: C:\Users\horse\Documents\Xilinx_Projects\AESencryption\matlab_test\test_build\test_dpi.sv
// Created: 2020-12-22 20:38:17
// Generated by MATLAB 9.9 and HDL Verifier 6.2

`timescale 1ns / 1ns

import test_dpi_pkg::*;



module test_dpi(
    input bit clk,
    input bit clk_enable,
    input bit reset,
    /* Simulink signal name: 'state' */
    input byte unsigned state ,
    /* Simulink signal name: 'state1' */
    input byte unsigned state1 ,
    /* Simulink signal name: 'state2' */
    input byte unsigned state2 ,
    /* Simulink signal name: 'state3' */
    input byte unsigned state3 ,
    /* Simulink signal name: 'state4' */
    input byte unsigned state4 ,
    /* Simulink signal name: 'state5' */
    input byte unsigned state5 ,
    /* Simulink signal name: 'state6' */
    input byte unsigned state6 ,
    /* Simulink signal name: 'state7' */
    input byte unsigned state7 ,
    /* Simulink signal name: 'state8' */
    input byte unsigned state8 ,
    /* Simulink signal name: 'state9' */
    input byte unsigned state9 ,
    /* Simulink signal name: 'state10' */
    input byte unsigned state10 ,
    /* Simulink signal name: 'state11' */
    input byte unsigned state11 ,
    /* Simulink signal name: 'state12' */
    input byte unsigned state12 ,
    /* Simulink signal name: 'state13' */
    input byte unsigned state13 ,
    /* Simulink signal name: 'state14' */
    input byte unsigned state14 ,
    /* Simulink signal name: 'state15' */
    input byte unsigned state15 ,
    /* Simulink signal name: 'temp_state' */
    output int unsigned temp_state ,
    /* Simulink signal name: 'temp_state1' */
    output int unsigned temp_state1 ,
    /* Simulink signal name: 'temp_state2' */
    output int unsigned temp_state2 ,
    /* Simulink signal name: 'temp_state3' */
    output int unsigned temp_state3 ,
    /* Simulink signal name: 'temp_state4' */
    output int unsigned temp_state4 ,
    /* Simulink signal name: 'temp_state5' */
    output int unsigned temp_state5 ,
    /* Simulink signal name: 'temp_state6' */
    output int unsigned temp_state6 ,
    /* Simulink signal name: 'temp_state7' */
    output int unsigned temp_state7 ,
    /* Simulink signal name: 'temp_state8' */
    output int unsigned temp_state8 ,
    /* Simulink signal name: 'temp_state9' */
    output int unsigned temp_state9 ,
    /* Simulink signal name: 'temp_state10' */
    output int unsigned temp_state10 ,
    /* Simulink signal name: 'temp_state11' */
    output int unsigned temp_state11 ,
    /* Simulink signal name: 'temp_state12' */
    output int unsigned temp_state12 ,
    /* Simulink signal name: 'temp_state13' */
    output int unsigned temp_state13 ,
    /* Simulink signal name: 'temp_state14' */
    output int unsigned temp_state14 ,
    /* Simulink signal name: 'temp_state15' */
    output int unsigned temp_state15 ,
    /* Simulink signal name: 'temp_state16' */
    output int unsigned temp_state16 ,
    /* Simulink signal name: 'temp_state17' */
    output int unsigned temp_state17 ,
    /* Simulink signal name: 'temp_state18' */
    output int unsigned temp_state18 ,
    /* Simulink signal name: 'temp_state19' */
    output int unsigned temp_state19 ,
    /* Simulink signal name: 'temp_state20' */
    output int unsigned temp_state20 ,
    /* Simulink signal name: 'temp_state21' */
    output int unsigned temp_state21 ,
    /* Simulink signal name: 'temp_state22' */
    output int unsigned temp_state22 ,
    /* Simulink signal name: 'temp_state23' */
    output int unsigned temp_state23 ,
    /* Simulink signal name: 'temp_state24' */
    output int unsigned temp_state24 ,
    /* Simulink signal name: 'temp_state25' */
    output int unsigned temp_state25 ,
    /* Simulink signal name: 'temp_state26' */
    output int unsigned temp_state26 ,
    /* Simulink signal name: 'temp_state27' */
    output int unsigned temp_state27 ,
    /* Simulink signal name: 'temp_state28' */
    output int unsigned temp_state28 ,
    /* Simulink signal name: 'temp_state29' */
    output int unsigned temp_state29 ,
    /* Simulink signal name: 'temp_state30' */
    output int unsigned temp_state30 ,
    /* Simulink signal name: 'temp_state31' */
    output int unsigned temp_state31 ,
    /* Simulink signal name: 'temp_state32' */
    output int unsigned temp_state32 ,
    /* Simulink signal name: 'temp_state33' */
    output int unsigned temp_state33 ,
    /* Simulink signal name: 'temp_state34' */
    output int unsigned temp_state34 ,
    /* Simulink signal name: 'temp_state35' */
    output int unsigned temp_state35 ,
    /* Simulink signal name: 'temp_state36' */
    output int unsigned temp_state36 ,
    /* Simulink signal name: 'temp_state37' */
    output int unsigned temp_state37 ,
    /* Simulink signal name: 'temp_state38' */
    output int unsigned temp_state38 ,
    /* Simulink signal name: 'temp_state39' */
    output int unsigned temp_state39 ,
    /* Simulink signal name: 'temp_state40' */
    output int unsigned temp_state40 ,
    /* Simulink signal name: 'temp_state41' */
    output int unsigned temp_state41 ,
    /* Simulink signal name: 'temp_state42' */
    output int unsigned temp_state42 ,
    /* Simulink signal name: 'temp_state43' */
    output int unsigned temp_state43 
);

    chandle objhandle=null;
     int unsigned temp_state_temp ;
     int unsigned temp_state1_temp ;
     int unsigned temp_state2_temp ;
     int unsigned temp_state3_temp ;
     int unsigned temp_state4_temp ;
     int unsigned temp_state5_temp ;
     int unsigned temp_state6_temp ;
     int unsigned temp_state7_temp ;
     int unsigned temp_state8_temp ;
     int unsigned temp_state9_temp ;
     int unsigned temp_state10_temp ;
     int unsigned temp_state11_temp ;
     int unsigned temp_state12_temp ;
     int unsigned temp_state13_temp ;
     int unsigned temp_state14_temp ;
     int unsigned temp_state15_temp ;
     int unsigned temp_state16_temp ;
     int unsigned temp_state17_temp ;
     int unsigned temp_state18_temp ;
     int unsigned temp_state19_temp ;
     int unsigned temp_state20_temp ;
     int unsigned temp_state21_temp ;
     int unsigned temp_state22_temp ;
     int unsigned temp_state23_temp ;
     int unsigned temp_state24_temp ;
     int unsigned temp_state25_temp ;
     int unsigned temp_state26_temp ;
     int unsigned temp_state27_temp ;
     int unsigned temp_state28_temp ;
     int unsigned temp_state29_temp ;
     int unsigned temp_state30_temp ;
     int unsigned temp_state31_temp ;
     int unsigned temp_state32_temp ;
     int unsigned temp_state33_temp ;
     int unsigned temp_state34_temp ;
     int unsigned temp_state35_temp ;
     int unsigned temp_state36_temp ;
     int unsigned temp_state37_temp ;
     int unsigned temp_state38_temp ;
     int unsigned temp_state39_temp ;
     int unsigned temp_state40_temp ;
     int unsigned temp_state41_temp ;
     int unsigned temp_state42_temp ;
     int unsigned temp_state43_temp ;
    

    initial begin
        objhandle = DPI_test_initialize(objhandle);
    end

    final begin
        DPI_test_terminate(objhandle);
    end

    always @(posedge clk or posedge reset) begin
        if(reset== 1'b1) begin
            objhandle=DPI_test_reset(objhandle,
            state, state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, temp_state_temp, temp_state1_temp, temp_state2_temp, temp_state3_temp, temp_state4_temp, temp_state5_temp, temp_state6_temp, temp_state7_temp, temp_state8_temp, temp_state9_temp, temp_state10_temp, temp_state11_temp, temp_state12_temp, temp_state13_temp, temp_state14_temp, temp_state15_temp, temp_state16_temp, temp_state17_temp, temp_state18_temp, temp_state19_temp, temp_state20_temp, temp_state21_temp, temp_state22_temp, temp_state23_temp, temp_state24_temp, temp_state25_temp, temp_state26_temp, temp_state27_temp, temp_state28_temp, temp_state29_temp, temp_state30_temp, temp_state31_temp, temp_state32_temp, temp_state33_temp, temp_state34_temp, temp_state35_temp, temp_state36_temp, temp_state37_temp, temp_state38_temp, temp_state39_temp, temp_state40_temp, temp_state41_temp, temp_state42_temp, temp_state43_temp);
            temp_state<=temp_state_temp;
            temp_state1<=temp_state1_temp;
            temp_state2<=temp_state2_temp;
            temp_state3<=temp_state3_temp;
            temp_state4<=temp_state4_temp;
            temp_state5<=temp_state5_temp;
            temp_state6<=temp_state6_temp;
            temp_state7<=temp_state7_temp;
            temp_state8<=temp_state8_temp;
            temp_state9<=temp_state9_temp;
            temp_state10<=temp_state10_temp;
            temp_state11<=temp_state11_temp;
            temp_state12<=temp_state12_temp;
            temp_state13<=temp_state13_temp;
            temp_state14<=temp_state14_temp;
            temp_state15<=temp_state15_temp;
            temp_state16<=temp_state16_temp;
            temp_state17<=temp_state17_temp;
            temp_state18<=temp_state18_temp;
            temp_state19<=temp_state19_temp;
            temp_state20<=temp_state20_temp;
            temp_state21<=temp_state21_temp;
            temp_state22<=temp_state22_temp;
            temp_state23<=temp_state23_temp;
            temp_state24<=temp_state24_temp;
            temp_state25<=temp_state25_temp;
            temp_state26<=temp_state26_temp;
            temp_state27<=temp_state27_temp;
            temp_state28<=temp_state28_temp;
            temp_state29<=temp_state29_temp;
            temp_state30<=temp_state30_temp;
            temp_state31<=temp_state31_temp;
            temp_state32<=temp_state32_temp;
            temp_state33<=temp_state33_temp;
            temp_state34<=temp_state34_temp;
            temp_state35<=temp_state35_temp;
            temp_state36<=temp_state36_temp;
            temp_state37<=temp_state37_temp;
            temp_state38<=temp_state38_temp;
            temp_state39<=temp_state39_temp;
            temp_state40<=temp_state40_temp;
            temp_state41<=temp_state41_temp;
            temp_state42<=temp_state42_temp;
            temp_state43<=temp_state43_temp;
            
        end
        else if(clk_enable) begin
            DPI_test_output(objhandle,
            state, state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, temp_state_temp, temp_state1_temp, temp_state2_temp, temp_state3_temp, temp_state4_temp, temp_state5_temp, temp_state6_temp, temp_state7_temp, temp_state8_temp, temp_state9_temp, temp_state10_temp, temp_state11_temp, temp_state12_temp, temp_state13_temp, temp_state14_temp, temp_state15_temp, temp_state16_temp, temp_state17_temp, temp_state18_temp, temp_state19_temp, temp_state20_temp, temp_state21_temp, temp_state22_temp, temp_state23_temp, temp_state24_temp, temp_state25_temp, temp_state26_temp, temp_state27_temp, temp_state28_temp, temp_state29_temp, temp_state30_temp, temp_state31_temp, temp_state32_temp, temp_state33_temp, temp_state34_temp, temp_state35_temp, temp_state36_temp, temp_state37_temp, temp_state38_temp, temp_state39_temp, temp_state40_temp, temp_state41_temp, temp_state42_temp, temp_state43_temp);
            DPI_test_update(objhandle,
            state, state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15);
            temp_state<=temp_state_temp;
            temp_state1<=temp_state1_temp;
            temp_state2<=temp_state2_temp;
            temp_state3<=temp_state3_temp;
            temp_state4<=temp_state4_temp;
            temp_state5<=temp_state5_temp;
            temp_state6<=temp_state6_temp;
            temp_state7<=temp_state7_temp;
            temp_state8<=temp_state8_temp;
            temp_state9<=temp_state9_temp;
            temp_state10<=temp_state10_temp;
            temp_state11<=temp_state11_temp;
            temp_state12<=temp_state12_temp;
            temp_state13<=temp_state13_temp;
            temp_state14<=temp_state14_temp;
            temp_state15<=temp_state15_temp;
            temp_state16<=temp_state16_temp;
            temp_state17<=temp_state17_temp;
            temp_state18<=temp_state18_temp;
            temp_state19<=temp_state19_temp;
            temp_state20<=temp_state20_temp;
            temp_state21<=temp_state21_temp;
            temp_state22<=temp_state22_temp;
            temp_state23<=temp_state23_temp;
            temp_state24<=temp_state24_temp;
            temp_state25<=temp_state25_temp;
            temp_state26<=temp_state26_temp;
            temp_state27<=temp_state27_temp;
            temp_state28<=temp_state28_temp;
            temp_state29<=temp_state29_temp;
            temp_state30<=temp_state30_temp;
            temp_state31<=temp_state31_temp;
            temp_state32<=temp_state32_temp;
            temp_state33<=temp_state33_temp;
            temp_state34<=temp_state34_temp;
            temp_state35<=temp_state35_temp;
            temp_state36<=temp_state36_temp;
            temp_state37<=temp_state37_temp;
            temp_state38<=temp_state38_temp;
            temp_state39<=temp_state39_temp;
            temp_state40<=temp_state40_temp;
            temp_state41<=temp_state41_temp;
            temp_state42<=temp_state42_temp;
            temp_state43<=temp_state43_temp;
            
        end
    end
endmodule
