/*

 File: C:\Users\horse\Documents\Xilinx_Projects\AESencryption\matlab_test\test_build\test_dpi.h
 Created: 2020-12-22 20:38:17
 Generated by MATLAB 9.9 and HDL Verifier 6.2

*/

#ifndef RTW_HEADER_test_dpi_h_
#define RTW_HEADER_test_dpi_h_

#ifdef __cplusplus
#define DPI_LINK_DECL extern "C"
#else
#define DPI_LINK_DECL
#endif

#ifndef DPI_DLL_EXPORT
#if defined(_MSC_VER) || defined(__LCC__)
#define DPI_DLL_EXPORT __declspec(dllexport)
#else
#define DPI_DLL_EXPORT 
#endif
#endif






DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_test_initialize(void* existhandle);
DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_test_reset(void* objhandle, uint8_T state, uint8_T state1, uint8_T state2, uint8_T state3, uint8_T state4, uint8_T state5, uint8_T state6, uint8_T state7, uint8_T state8, uint8_T state9, uint8_T state10, uint8_T state11, uint8_T state12, uint8_T state13, uint8_T state14, uint8_T state15, uint32_T* temp_state, uint32_T* temp_state1, uint32_T* temp_state2, uint32_T* temp_state3, uint32_T* temp_state4, uint32_T* temp_state5, uint32_T* temp_state6, uint32_T* temp_state7, uint32_T* temp_state8, uint32_T* temp_state9, uint32_T* temp_state10, uint32_T* temp_state11, uint32_T* temp_state12, uint32_T* temp_state13, uint32_T* temp_state14, uint32_T* temp_state15, uint32_T* temp_state16, uint32_T* temp_state17, uint32_T* temp_state18, uint32_T* temp_state19, uint32_T* temp_state20, uint32_T* temp_state21, uint32_T* temp_state22, uint32_T* temp_state23, uint32_T* temp_state24, uint32_T* temp_state25, uint32_T* temp_state26, uint32_T* temp_state27, uint32_T* temp_state28, uint32_T* temp_state29, uint32_T* temp_state30, uint32_T* temp_state31, uint32_T* temp_state32, uint32_T* temp_state33, uint32_T* temp_state34, uint32_T* temp_state35, uint32_T* temp_state36, uint32_T* temp_state37, uint32_T* temp_state38, uint32_T* temp_state39, uint32_T* temp_state40, uint32_T* temp_state41, uint32_T* temp_state42, uint32_T* temp_state43);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_test_output(void* objhandle, uint8_T state, uint8_T state1, uint8_T state2, uint8_T state3, uint8_T state4, uint8_T state5, uint8_T state6, uint8_T state7, uint8_T state8, uint8_T state9, uint8_T state10, uint8_T state11, uint8_T state12, uint8_T state13, uint8_T state14, uint8_T state15, uint32_T* temp_state, uint32_T* temp_state1, uint32_T* temp_state2, uint32_T* temp_state3, uint32_T* temp_state4, uint32_T* temp_state5, uint32_T* temp_state6, uint32_T* temp_state7, uint32_T* temp_state8, uint32_T* temp_state9, uint32_T* temp_state10, uint32_T* temp_state11, uint32_T* temp_state12, uint32_T* temp_state13, uint32_T* temp_state14, uint32_T* temp_state15, uint32_T* temp_state16, uint32_T* temp_state17, uint32_T* temp_state18, uint32_T* temp_state19, uint32_T* temp_state20, uint32_T* temp_state21, uint32_T* temp_state22, uint32_T* temp_state23, uint32_T* temp_state24, uint32_T* temp_state25, uint32_T* temp_state26, uint32_T* temp_state27, uint32_T* temp_state28, uint32_T* temp_state29, uint32_T* temp_state30, uint32_T* temp_state31, uint32_T* temp_state32, uint32_T* temp_state33, uint32_T* temp_state34, uint32_T* temp_state35, uint32_T* temp_state36, uint32_T* temp_state37, uint32_T* temp_state38, uint32_T* temp_state39, uint32_T* temp_state40, uint32_T* temp_state41, uint32_T* temp_state42, uint32_T* temp_state43);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_test_update(void* objhandle, uint8_T state, uint8_T state1, uint8_T state2, uint8_T state3, uint8_T state4, uint8_T state5, uint8_T state6, uint8_T state7, uint8_T state8, uint8_T state9, uint8_T state10, uint8_T state11, uint8_T state12, uint8_T state13, uint8_T state14, uint8_T state15);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_test_terminate(void* objhandle);

#endif /*RTW_HEADER_test_dpi_h_*/

