@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 07 03:43:06 -0400 2020
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim hamming_check_tb_behav -key {Behavioral:sim_1:Functional:hamming_check_tb} -tclbatch hamming_check_tb.tcl -view C:/Users/horse/Documents/Xilinx_Projects/project_6_2/hamming_check_tb_behav.wcfg -log simulate.log"
call xsim  hamming_check_tb_behav -key {Behavioral:sim_1:Functional:hamming_check_tb} -tclbatch hamming_check_tb.tcl -view C:/Users/horse/Documents/Xilinx_Projects/project_6_2/hamming_check_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
