// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test3\test3.v
// Created: 2020-12-26 12:54:20
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: test3
// Source Path: test3
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module test3
          (data1,
           temp_state1);


  input   [31:0] data1;  // uint32
  output  [31:0] temp_state1;  // uint32


  wire [31:0] ret_word;  // uint32


  SubWord u_SubWord (.word(data1),  // uint32
                     .ret_word(ret_word)  // uint32
                     );

  assign temp_state1 = ret_word;

endmodule  // test3

