/*

 File: C:\Users\horse\Documents\Xilinx_Projects\matlab_test\test_build\test_dpi.c
 Created: 2020-12-12 15:18:20
 Generated by MATLAB 9.9 and HDL Verifier 6.2

*/

#include "test.h"
#include "test_dpi.h"

#ifndef RT_MEMORY_ALLOCATION_ERROR_DEF
#define RT_MEMORY_ALLOCATION_ERROR_DEF
const char *RT_MEMORY_ALLOCATION_ERROR = "memory allocation error";
#endif
static RT_MODEL_test_T* RT_MODEL_test = NULL;







DPI_DLL_EXPORT void* DPI_test_initialize(void* existhandle)
{
RT_MODEL_test_T* objhandle;

if(existhandle==NULL)
{
	objhandle=test();
}else{
	objhandle=(RT_MODEL_test_T*)existhandle;
}
test_initialize(objhandle);


return (void*)objhandle;
}

DPI_DLL_EXPORT void* DPI_test_reset(void* objhandle, uint32_T in1, uint32_T in2, uint32_T in3, uint32_T* out1)
{
    DPI_test_terminate(objhandle);
    objhandle=NULL;
    objhandle=DPI_test_initialize(NULL);
    DPI_test_output(objhandle,in1,in2,in3,out1);
    DPI_test_terminate(objhandle);
    objhandle=NULL;
    return DPI_test_initialize(NULL);
    
}

DPI_DLL_EXPORT void DPI_test_output(void* objhandle, uint32_T in1, uint32_T in2, uint32_T in3, uint32_T* out1)
{
    
    
    uint32_T* in1_Ptr = &in1;
    uint32_T* in2_Ptr = &in2;
    uint32_T* in3_Ptr = &in3;
    
    uint32_T* RT_MODEL_test_input_in1_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->in1);
    uint32_T* RT_MODEL_test_input_in2_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->in2);
    uint32_T* RT_MODEL_test_input_in3_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->in3);
    
    uint32_T* out1_Ptr = out1;
    
    uint32_T* RT_MODEL_test_output_out1_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->out1);
    
    
    
    *RT_MODEL_test_input_in1_Ptr=*in1_Ptr;
    *RT_MODEL_test_input_in2_Ptr=*in2_Ptr;
    *RT_MODEL_test_input_in3_Ptr=*in3_Ptr;
    
    test_output(((RT_MODEL_test_T*) objhandle ));
    
    
    *out1_Ptr=*RT_MODEL_test_output_out1_Ptr;
    
}

DPI_DLL_EXPORT void DPI_test_update(void* objhandle, uint32_T in1, uint32_T in2, uint32_T in3)
{
    
    
    uint32_T* in1_Ptr = &in1;
    uint32_T* in2_Ptr = &in2;
    uint32_T* in3_Ptr = &in3;
    
    uint32_T* RT_MODEL_test_input_in1_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->in1);
    uint32_T* RT_MODEL_test_input_in2_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->in2);
    uint32_T* RT_MODEL_test_input_in3_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->in3);
    
    
    
    *RT_MODEL_test_input_in1_Ptr=*in1_Ptr;
    *RT_MODEL_test_input_in2_Ptr=*in2_Ptr;
    *RT_MODEL_test_input_in3_Ptr=*in3_Ptr;
    
    test_update(((RT_MODEL_test_T*) objhandle ));
}

DPI_DLL_EXPORT void DPI_test_terminate(void* objhandle)
{
    test_terminate(((RT_MODEL_test_T*)objhandle));
}


