// File: C:\Users\horse\Documents\Xilinx_Projects\matlab_test\test_build\test_dpi.sv
// Created: 2020-12-12 15:18:20
// Generated by MATLAB 9.9 and HDL Verifier 6.2

`timescale 1ns / 1ns

import test_dpi_pkg::*;



module test_dpi(
    input bit clk,
    input bit clk_enable,
    input bit reset,
    /* Simulink signal name: 'in1' */
    input int unsigned in1 ,
    /* Simulink signal name: 'in2' */
    input int unsigned in2 ,
    /* Simulink signal name: 'in3' */
    input int unsigned in3 ,
    /* Simulink signal name: 'out1' */
    output int unsigned out1 
);

    chandle objhandle=null;
     int unsigned out1_temp ;
    

    initial begin
        objhandle = DPI_test_initialize(objhandle);
    end

    final begin
        DPI_test_terminate(objhandle);
    end

    always @(posedge clk or posedge reset) begin
        if(reset== 1'b1) begin
            objhandle=DPI_test_reset(objhandle,
            in1, in2, in3, out1_temp);
            out1<=out1_temp;
            
        end
        else if(clk_enable) begin
            DPI_test_output(objhandle,
            in1, in2, in3, out1_temp);
            DPI_test_update(objhandle,
            in1, in2, in3);
            out1<=out1_temp;
            
        end
    end
endmodule
