// File: C:\Users\horse\Documents\Xilinx_Projects\matlab_test\test_build\test_dpi_pkg.sv
// Created: 2020-12-12 15:18:20
// Generated by MATLAB 9.9 and HDL Verifier 6.2

`timescale 1ns / 1ns
package test_dpi_pkg;

// Declare imported C functions
import "DPI-C" function chandle DPI_test_initialize(chandle existhandle);
import "DPI-C" function chandle DPI_test_reset(input chandle objhandle,
/*Simulink signal name: 'in1'*/
input int unsigned in1,
/*Simulink signal name: 'in2'*/
input int unsigned in2,
/*Simulink signal name: 'in3'*/
input int unsigned in3,
/*Simulink signal name: 'out1'*/
inout int unsigned out1);
import "DPI-C" function void DPI_test_output(input chandle objhandle,
/*Simulink signal name: 'in1'*/
input int unsigned in1,
/*Simulink signal name: 'in2'*/
input int unsigned in2,
/*Simulink signal name: 'in3'*/
input int unsigned in3,
/*Simulink signal name: 'out1'*/
inout int unsigned out1);
import "DPI-C" function void DPI_test_update(input chandle objhandle,
/*Simulink signal name: 'in1'*/
input int unsigned in1,
/*Simulink signal name: 'in2'*/
input int unsigned in2,
/*Simulink signal name: 'in3'*/
input int unsigned in3);
import "DPI-C" function void DPI_test_terminate(input chandle objhandle);








endpackage : test_dpi_pkg
