/*

 File: C:\Users\horse\Documents\Xilinx_Projects\AESencryption\matlab_test\test_build\test_dpi.c
 Created: 2020-12-22 20:38:17
 Generated by MATLAB 9.9 and HDL Verifier 6.2

*/

#include "test.h"
#include "test_dpi.h"

#ifndef RT_MEMORY_ALLOCATION_ERROR_DEF
#define RT_MEMORY_ALLOCATION_ERROR_DEF
const char *RT_MEMORY_ALLOCATION_ERROR = "memory allocation error";
#endif
static RT_MODEL_test_T* RT_MODEL_test = NULL;







DPI_DLL_EXPORT void* DPI_test_initialize(void* existhandle)
{
RT_MODEL_test_T* objhandle;

if(existhandle==NULL)
{
	objhandle=test();
}else{
	objhandle=(RT_MODEL_test_T*)existhandle;
}
test_initialize(objhandle);


return (void*)objhandle;
}

DPI_DLL_EXPORT void* DPI_test_reset(void* objhandle, uint8_T state, uint8_T state1, uint8_T state2, uint8_T state3, uint8_T state4, uint8_T state5, uint8_T state6, uint8_T state7, uint8_T state8, uint8_T state9, uint8_T state10, uint8_T state11, uint8_T state12, uint8_T state13, uint8_T state14, uint8_T state15, uint32_T* temp_state, uint32_T* temp_state1, uint32_T* temp_state2, uint32_T* temp_state3, uint32_T* temp_state4, uint32_T* temp_state5, uint32_T* temp_state6, uint32_T* temp_state7, uint32_T* temp_state8, uint32_T* temp_state9, uint32_T* temp_state10, uint32_T* temp_state11, uint32_T* temp_state12, uint32_T* temp_state13, uint32_T* temp_state14, uint32_T* temp_state15, uint32_T* temp_state16, uint32_T* temp_state17, uint32_T* temp_state18, uint32_T* temp_state19, uint32_T* temp_state20, uint32_T* temp_state21, uint32_T* temp_state22, uint32_T* temp_state23, uint32_T* temp_state24, uint32_T* temp_state25, uint32_T* temp_state26, uint32_T* temp_state27, uint32_T* temp_state28, uint32_T* temp_state29, uint32_T* temp_state30, uint32_T* temp_state31, uint32_T* temp_state32, uint32_T* temp_state33, uint32_T* temp_state34, uint32_T* temp_state35, uint32_T* temp_state36, uint32_T* temp_state37, uint32_T* temp_state38, uint32_T* temp_state39, uint32_T* temp_state40, uint32_T* temp_state41, uint32_T* temp_state42, uint32_T* temp_state43)
{
    DPI_test_terminate(objhandle);
    objhandle=NULL;
    objhandle=DPI_test_initialize(NULL);
    DPI_test_output(objhandle,state,state1,state2,state3,state4,state5,state6,state7,state8,state9,state10,state11,state12,state13,state14,state15,temp_state,temp_state1,temp_state2,temp_state3,temp_state4,temp_state5,temp_state6,temp_state7,temp_state8,temp_state9,temp_state10,temp_state11,temp_state12,temp_state13,temp_state14,temp_state15,temp_state16,temp_state17,temp_state18,temp_state19,temp_state20,temp_state21,temp_state22,temp_state23,temp_state24,temp_state25,temp_state26,temp_state27,temp_state28,temp_state29,temp_state30,temp_state31,temp_state32,temp_state33,temp_state34,temp_state35,temp_state36,temp_state37,temp_state38,temp_state39,temp_state40,temp_state41,temp_state42,temp_state43);
    DPI_test_terminate(objhandle);
    objhandle=NULL;
    return DPI_test_initialize(NULL);
    
}

DPI_DLL_EXPORT void DPI_test_output(void* objhandle, uint8_T state, uint8_T state1, uint8_T state2, uint8_T state3, uint8_T state4, uint8_T state5, uint8_T state6, uint8_T state7, uint8_T state8, uint8_T state9, uint8_T state10, uint8_T state11, uint8_T state12, uint8_T state13, uint8_T state14, uint8_T state15, uint32_T* temp_state, uint32_T* temp_state1, uint32_T* temp_state2, uint32_T* temp_state3, uint32_T* temp_state4, uint32_T* temp_state5, uint32_T* temp_state6, uint32_T* temp_state7, uint32_T* temp_state8, uint32_T* temp_state9, uint32_T* temp_state10, uint32_T* temp_state11, uint32_T* temp_state12, uint32_T* temp_state13, uint32_T* temp_state14, uint32_T* temp_state15, uint32_T* temp_state16, uint32_T* temp_state17, uint32_T* temp_state18, uint32_T* temp_state19, uint32_T* temp_state20, uint32_T* temp_state21, uint32_T* temp_state22, uint32_T* temp_state23, uint32_T* temp_state24, uint32_T* temp_state25, uint32_T* temp_state26, uint32_T* temp_state27, uint32_T* temp_state28, uint32_T* temp_state29, uint32_T* temp_state30, uint32_T* temp_state31, uint32_T* temp_state32, uint32_T* temp_state33, uint32_T* temp_state34, uint32_T* temp_state35, uint32_T* temp_state36, uint32_T* temp_state37, uint32_T* temp_state38, uint32_T* temp_state39, uint32_T* temp_state40, uint32_T* temp_state41, uint32_T* temp_state42, uint32_T* temp_state43)
{
    
    
    uint8_T* state_Ptr = &state;
    uint8_T* state1_Ptr = &state1;
    uint8_T* state2_Ptr = &state2;
    uint8_T* state3_Ptr = &state3;
    uint8_T* state4_Ptr = &state4;
    uint8_T* state5_Ptr = &state5;
    uint8_T* state6_Ptr = &state6;
    uint8_T* state7_Ptr = &state7;
    uint8_T* state8_Ptr = &state8;
    uint8_T* state9_Ptr = &state9;
    uint8_T* state10_Ptr = &state10;
    uint8_T* state11_Ptr = &state11;
    uint8_T* state12_Ptr = &state12;
    uint8_T* state13_Ptr = &state13;
    uint8_T* state14_Ptr = &state14;
    uint8_T* state15_Ptr = &state15;
    
    uint8_T* RT_MODEL_test_input_state_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state);
    uint8_T* RT_MODEL_test_input_state1_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state1);
    uint8_T* RT_MODEL_test_input_state2_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state2);
    uint8_T* RT_MODEL_test_input_state3_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state3);
    uint8_T* RT_MODEL_test_input_state4_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state4);
    uint8_T* RT_MODEL_test_input_state5_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state5);
    uint8_T* RT_MODEL_test_input_state6_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state6);
    uint8_T* RT_MODEL_test_input_state7_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state7);
    uint8_T* RT_MODEL_test_input_state8_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state8);
    uint8_T* RT_MODEL_test_input_state9_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state9);
    uint8_T* RT_MODEL_test_input_state10_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state10);
    uint8_T* RT_MODEL_test_input_state11_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state11);
    uint8_T* RT_MODEL_test_input_state12_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state12);
    uint8_T* RT_MODEL_test_input_state13_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state13);
    uint8_T* RT_MODEL_test_input_state14_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state14);
    uint8_T* RT_MODEL_test_input_state15_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state15);
    
    uint32_T* temp_state_Ptr = temp_state;
    uint32_T* temp_state1_Ptr = temp_state1;
    uint32_T* temp_state2_Ptr = temp_state2;
    uint32_T* temp_state3_Ptr = temp_state3;
    uint32_T* temp_state4_Ptr = temp_state4;
    uint32_T* temp_state5_Ptr = temp_state5;
    uint32_T* temp_state6_Ptr = temp_state6;
    uint32_T* temp_state7_Ptr = temp_state7;
    uint32_T* temp_state8_Ptr = temp_state8;
    uint32_T* temp_state9_Ptr = temp_state9;
    uint32_T* temp_state10_Ptr = temp_state10;
    uint32_T* temp_state11_Ptr = temp_state11;
    uint32_T* temp_state12_Ptr = temp_state12;
    uint32_T* temp_state13_Ptr = temp_state13;
    uint32_T* temp_state14_Ptr = temp_state14;
    uint32_T* temp_state15_Ptr = temp_state15;
    uint32_T* temp_state16_Ptr = temp_state16;
    uint32_T* temp_state17_Ptr = temp_state17;
    uint32_T* temp_state18_Ptr = temp_state18;
    uint32_T* temp_state19_Ptr = temp_state19;
    uint32_T* temp_state20_Ptr = temp_state20;
    uint32_T* temp_state21_Ptr = temp_state21;
    uint32_T* temp_state22_Ptr = temp_state22;
    uint32_T* temp_state23_Ptr = temp_state23;
    uint32_T* temp_state24_Ptr = temp_state24;
    uint32_T* temp_state25_Ptr = temp_state25;
    uint32_T* temp_state26_Ptr = temp_state26;
    uint32_T* temp_state27_Ptr = temp_state27;
    uint32_T* temp_state28_Ptr = temp_state28;
    uint32_T* temp_state29_Ptr = temp_state29;
    uint32_T* temp_state30_Ptr = temp_state30;
    uint32_T* temp_state31_Ptr = temp_state31;
    uint32_T* temp_state32_Ptr = temp_state32;
    uint32_T* temp_state33_Ptr = temp_state33;
    uint32_T* temp_state34_Ptr = temp_state34;
    uint32_T* temp_state35_Ptr = temp_state35;
    uint32_T* temp_state36_Ptr = temp_state36;
    uint32_T* temp_state37_Ptr = temp_state37;
    uint32_T* temp_state38_Ptr = temp_state38;
    uint32_T* temp_state39_Ptr = temp_state39;
    uint32_T* temp_state40_Ptr = temp_state40;
    uint32_T* temp_state41_Ptr = temp_state41;
    uint32_T* temp_state42_Ptr = temp_state42;
    uint32_T* temp_state43_Ptr = temp_state43;
    
    uint32_T* RT_MODEL_test_output_temp_state_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state);
    uint32_T* RT_MODEL_test_output_temp_state1_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state1);
    uint32_T* RT_MODEL_test_output_temp_state2_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state2);
    uint32_T* RT_MODEL_test_output_temp_state3_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state3);
    uint32_T* RT_MODEL_test_output_temp_state4_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state4);
    uint32_T* RT_MODEL_test_output_temp_state5_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state5);
    uint32_T* RT_MODEL_test_output_temp_state6_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state6);
    uint32_T* RT_MODEL_test_output_temp_state7_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state7);
    uint32_T* RT_MODEL_test_output_temp_state8_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state8);
    uint32_T* RT_MODEL_test_output_temp_state9_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state9);
    uint32_T* RT_MODEL_test_output_temp_state10_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state10);
    uint32_T* RT_MODEL_test_output_temp_state11_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state11);
    uint32_T* RT_MODEL_test_output_temp_state12_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state12);
    uint32_T* RT_MODEL_test_output_temp_state13_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state13);
    uint32_T* RT_MODEL_test_output_temp_state14_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state14);
    uint32_T* RT_MODEL_test_output_temp_state15_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state15);
    uint32_T* RT_MODEL_test_output_temp_state16_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state16);
    uint32_T* RT_MODEL_test_output_temp_state17_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state17);
    uint32_T* RT_MODEL_test_output_temp_state18_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state18);
    uint32_T* RT_MODEL_test_output_temp_state19_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state19);
    uint32_T* RT_MODEL_test_output_temp_state20_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state20);
    uint32_T* RT_MODEL_test_output_temp_state21_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state21);
    uint32_T* RT_MODEL_test_output_temp_state22_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state22);
    uint32_T* RT_MODEL_test_output_temp_state23_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state23);
    uint32_T* RT_MODEL_test_output_temp_state24_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state24);
    uint32_T* RT_MODEL_test_output_temp_state25_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state25);
    uint32_T* RT_MODEL_test_output_temp_state26_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state26);
    uint32_T* RT_MODEL_test_output_temp_state27_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state27);
    uint32_T* RT_MODEL_test_output_temp_state28_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state28);
    uint32_T* RT_MODEL_test_output_temp_state29_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state29);
    uint32_T* RT_MODEL_test_output_temp_state30_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state30);
    uint32_T* RT_MODEL_test_output_temp_state31_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state31);
    uint32_T* RT_MODEL_test_output_temp_state32_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state32);
    uint32_T* RT_MODEL_test_output_temp_state33_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state33);
    uint32_T* RT_MODEL_test_output_temp_state34_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state34);
    uint32_T* RT_MODEL_test_output_temp_state35_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state35);
    uint32_T* RT_MODEL_test_output_temp_state36_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state36);
    uint32_T* RT_MODEL_test_output_temp_state37_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state37);
    uint32_T* RT_MODEL_test_output_temp_state38_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state38);
    uint32_T* RT_MODEL_test_output_temp_state39_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state39);
    uint32_T* RT_MODEL_test_output_temp_state40_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state40);
    uint32_T* RT_MODEL_test_output_temp_state41_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state41);
    uint32_T* RT_MODEL_test_output_temp_state42_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state42);
    uint32_T* RT_MODEL_test_output_temp_state43_Ptr = &(((RT_MODEL_test_T*) objhandle )->outputs->temp_state43);
    
    
    
    *RT_MODEL_test_input_state_Ptr=*state_Ptr;
    *RT_MODEL_test_input_state1_Ptr=*state1_Ptr;
    *RT_MODEL_test_input_state2_Ptr=*state2_Ptr;
    *RT_MODEL_test_input_state3_Ptr=*state3_Ptr;
    *RT_MODEL_test_input_state4_Ptr=*state4_Ptr;
    *RT_MODEL_test_input_state5_Ptr=*state5_Ptr;
    *RT_MODEL_test_input_state6_Ptr=*state6_Ptr;
    *RT_MODEL_test_input_state7_Ptr=*state7_Ptr;
    *RT_MODEL_test_input_state8_Ptr=*state8_Ptr;
    *RT_MODEL_test_input_state9_Ptr=*state9_Ptr;
    *RT_MODEL_test_input_state10_Ptr=*state10_Ptr;
    *RT_MODEL_test_input_state11_Ptr=*state11_Ptr;
    *RT_MODEL_test_input_state12_Ptr=*state12_Ptr;
    *RT_MODEL_test_input_state13_Ptr=*state13_Ptr;
    *RT_MODEL_test_input_state14_Ptr=*state14_Ptr;
    *RT_MODEL_test_input_state15_Ptr=*state15_Ptr;
    
    test_output(((RT_MODEL_test_T*) objhandle ));
    
    
    *temp_state_Ptr=*RT_MODEL_test_output_temp_state_Ptr;
    *temp_state1_Ptr=*RT_MODEL_test_output_temp_state1_Ptr;
    *temp_state2_Ptr=*RT_MODEL_test_output_temp_state2_Ptr;
    *temp_state3_Ptr=*RT_MODEL_test_output_temp_state3_Ptr;
    *temp_state4_Ptr=*RT_MODEL_test_output_temp_state4_Ptr;
    *temp_state5_Ptr=*RT_MODEL_test_output_temp_state5_Ptr;
    *temp_state6_Ptr=*RT_MODEL_test_output_temp_state6_Ptr;
    *temp_state7_Ptr=*RT_MODEL_test_output_temp_state7_Ptr;
    *temp_state8_Ptr=*RT_MODEL_test_output_temp_state8_Ptr;
    *temp_state9_Ptr=*RT_MODEL_test_output_temp_state9_Ptr;
    *temp_state10_Ptr=*RT_MODEL_test_output_temp_state10_Ptr;
    *temp_state11_Ptr=*RT_MODEL_test_output_temp_state11_Ptr;
    *temp_state12_Ptr=*RT_MODEL_test_output_temp_state12_Ptr;
    *temp_state13_Ptr=*RT_MODEL_test_output_temp_state13_Ptr;
    *temp_state14_Ptr=*RT_MODEL_test_output_temp_state14_Ptr;
    *temp_state15_Ptr=*RT_MODEL_test_output_temp_state15_Ptr;
    *temp_state16_Ptr=*RT_MODEL_test_output_temp_state16_Ptr;
    *temp_state17_Ptr=*RT_MODEL_test_output_temp_state17_Ptr;
    *temp_state18_Ptr=*RT_MODEL_test_output_temp_state18_Ptr;
    *temp_state19_Ptr=*RT_MODEL_test_output_temp_state19_Ptr;
    *temp_state20_Ptr=*RT_MODEL_test_output_temp_state20_Ptr;
    *temp_state21_Ptr=*RT_MODEL_test_output_temp_state21_Ptr;
    *temp_state22_Ptr=*RT_MODEL_test_output_temp_state22_Ptr;
    *temp_state23_Ptr=*RT_MODEL_test_output_temp_state23_Ptr;
    *temp_state24_Ptr=*RT_MODEL_test_output_temp_state24_Ptr;
    *temp_state25_Ptr=*RT_MODEL_test_output_temp_state25_Ptr;
    *temp_state26_Ptr=*RT_MODEL_test_output_temp_state26_Ptr;
    *temp_state27_Ptr=*RT_MODEL_test_output_temp_state27_Ptr;
    *temp_state28_Ptr=*RT_MODEL_test_output_temp_state28_Ptr;
    *temp_state29_Ptr=*RT_MODEL_test_output_temp_state29_Ptr;
    *temp_state30_Ptr=*RT_MODEL_test_output_temp_state30_Ptr;
    *temp_state31_Ptr=*RT_MODEL_test_output_temp_state31_Ptr;
    *temp_state32_Ptr=*RT_MODEL_test_output_temp_state32_Ptr;
    *temp_state33_Ptr=*RT_MODEL_test_output_temp_state33_Ptr;
    *temp_state34_Ptr=*RT_MODEL_test_output_temp_state34_Ptr;
    *temp_state35_Ptr=*RT_MODEL_test_output_temp_state35_Ptr;
    *temp_state36_Ptr=*RT_MODEL_test_output_temp_state36_Ptr;
    *temp_state37_Ptr=*RT_MODEL_test_output_temp_state37_Ptr;
    *temp_state38_Ptr=*RT_MODEL_test_output_temp_state38_Ptr;
    *temp_state39_Ptr=*RT_MODEL_test_output_temp_state39_Ptr;
    *temp_state40_Ptr=*RT_MODEL_test_output_temp_state40_Ptr;
    *temp_state41_Ptr=*RT_MODEL_test_output_temp_state41_Ptr;
    *temp_state42_Ptr=*RT_MODEL_test_output_temp_state42_Ptr;
    *temp_state43_Ptr=*RT_MODEL_test_output_temp_state43_Ptr;
    
}

DPI_DLL_EXPORT void DPI_test_update(void* objhandle, uint8_T state, uint8_T state1, uint8_T state2, uint8_T state3, uint8_T state4, uint8_T state5, uint8_T state6, uint8_T state7, uint8_T state8, uint8_T state9, uint8_T state10, uint8_T state11, uint8_T state12, uint8_T state13, uint8_T state14, uint8_T state15)
{
    
    
    uint8_T* state_Ptr = &state;
    uint8_T* state1_Ptr = &state1;
    uint8_T* state2_Ptr = &state2;
    uint8_T* state3_Ptr = &state3;
    uint8_T* state4_Ptr = &state4;
    uint8_T* state5_Ptr = &state5;
    uint8_T* state6_Ptr = &state6;
    uint8_T* state7_Ptr = &state7;
    uint8_T* state8_Ptr = &state8;
    uint8_T* state9_Ptr = &state9;
    uint8_T* state10_Ptr = &state10;
    uint8_T* state11_Ptr = &state11;
    uint8_T* state12_Ptr = &state12;
    uint8_T* state13_Ptr = &state13;
    uint8_T* state14_Ptr = &state14;
    uint8_T* state15_Ptr = &state15;
    
    uint8_T* RT_MODEL_test_input_state_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state);
    uint8_T* RT_MODEL_test_input_state1_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state1);
    uint8_T* RT_MODEL_test_input_state2_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state2);
    uint8_T* RT_MODEL_test_input_state3_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state3);
    uint8_T* RT_MODEL_test_input_state4_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state4);
    uint8_T* RT_MODEL_test_input_state5_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state5);
    uint8_T* RT_MODEL_test_input_state6_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state6);
    uint8_T* RT_MODEL_test_input_state7_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state7);
    uint8_T* RT_MODEL_test_input_state8_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state8);
    uint8_T* RT_MODEL_test_input_state9_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state9);
    uint8_T* RT_MODEL_test_input_state10_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state10);
    uint8_T* RT_MODEL_test_input_state11_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state11);
    uint8_T* RT_MODEL_test_input_state12_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state12);
    uint8_T* RT_MODEL_test_input_state13_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state13);
    uint8_T* RT_MODEL_test_input_state14_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state14);
    uint8_T* RT_MODEL_test_input_state15_Ptr = &(((RT_MODEL_test_T*) objhandle )->inputs->state15);
    
    
    
    *RT_MODEL_test_input_state_Ptr=*state_Ptr;
    *RT_MODEL_test_input_state1_Ptr=*state1_Ptr;
    *RT_MODEL_test_input_state2_Ptr=*state2_Ptr;
    *RT_MODEL_test_input_state3_Ptr=*state3_Ptr;
    *RT_MODEL_test_input_state4_Ptr=*state4_Ptr;
    *RT_MODEL_test_input_state5_Ptr=*state5_Ptr;
    *RT_MODEL_test_input_state6_Ptr=*state6_Ptr;
    *RT_MODEL_test_input_state7_Ptr=*state7_Ptr;
    *RT_MODEL_test_input_state8_Ptr=*state8_Ptr;
    *RT_MODEL_test_input_state9_Ptr=*state9_Ptr;
    *RT_MODEL_test_input_state10_Ptr=*state10_Ptr;
    *RT_MODEL_test_input_state11_Ptr=*state11_Ptr;
    *RT_MODEL_test_input_state12_Ptr=*state12_Ptr;
    *RT_MODEL_test_input_state13_Ptr=*state13_Ptr;
    *RT_MODEL_test_input_state14_Ptr=*state14_Ptr;
    *RT_MODEL_test_input_state15_Ptr=*state15_Ptr;
    
    test_update(((RT_MODEL_test_T*) objhandle ));
}

DPI_DLL_EXPORT void DPI_test_terminate(void* objhandle)
{
    test_terminate(((RT_MODEL_test_T*)objhandle));
}


