/*

 File: C:\Users\horse\Documents\Xilinx_Projects\matlab_test\test_build\test_dpi.h
 Created: 2020-12-12 15:18:20
 Generated by MATLAB 9.9 and HDL Verifier 6.2

*/

#ifndef RTW_HEADER_test_dpi_h_
#define RTW_HEADER_test_dpi_h_

#ifdef __cplusplus
#define DPI_LINK_DECL extern "C"
#else
#define DPI_LINK_DECL
#endif

#ifndef DPI_DLL_EXPORT
#if defined(_MSC_VER) || defined(__LCC__)
#define DPI_DLL_EXPORT __declspec(dllexport)
#else
#define DPI_DLL_EXPORT 
#endif
#endif






DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_test_initialize(void* existhandle);
DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_test_reset(void* objhandle, uint32_T in1, uint32_T in2, uint32_T in3, uint32_T* out1);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_test_output(void* objhandle, uint32_T in1, uint32_T in2, uint32_T in3, uint32_T* out1);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_test_update(void* objhandle, uint32_T in1, uint32_T in2, uint32_T in3);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_test_terminate(void* objhandle);

#endif /*RTW_HEADER_test_dpi_h_*/

