// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test3\RotWord.v
// Created: 2020-12-26 12:50:55
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RotWord
// Source Path: test3/RotWord
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RotWord (word, ret_word);


  input   [31:0] word;  // uint32
  output wire [31:0] ret_word;  // uint32

  assign ret_word = {word[23:16], word[15:8], word[7:0], word[31:24]};

endmodule  // RotWord