// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test\KeyExpansion.v
// Created: 2020-12-25 14:45:37
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: KeyExpansion
// Source Path: test/Subsystem/KeyExpansion
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module KeyExpansion();
    parameter BLOCK_DATA_SIZE_1 = 8;
    parameter BLOCK_DATA_SIZE_2 = 32;
    parameter BLOCK_AMOUNT_1 = 16;
    parameter BLOCK_AMOUNT_2 = 44;
    
    //USING RAM
    reg [BLOCK_DATA_SIZE_1-1:0] KEY_RAM [BLOCK_AMOUNT_1-1:0];
    reg [BLOCK_DATA_SIZE_1-1:0] STATE_RAM [BLOCK_AMOUNT_1-1:0];
    reg [BLOCK_DATA_SIZE_2-1:0] EXPANDED_KEY_RAM [BLOCK_AMOUNT_2-1:0];
    
    
    
endmodule  // KeyExpansion

