// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test\Module_one1.v
// Created: 2020-12-12 15:19:20
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Module_one1
// Source Path: test/Module_one1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Module_one1
          (input1,
           input2,
           input3,
           y);


  input   [31:0] input1;  // uint32
  input   [31:0] input2;  // uint32
  input   [31:0] input3;  // uint32
  output  [31:0] y;  // uint32


  wire [63:0] mul_temp;  // ufix64
  wire [31:0] cast;  // uint32
  wire [63:0] mul_temp_1;  // ufix64


  assign mul_temp = input1 * input2;
  assign cast = (mul_temp[63:32] != 32'b00000000000000000000000000000000 ? 32'b11111111111111111111111111111111 :
              mul_temp[31:0]);
  assign mul_temp_1 = cast * input3;
  assign y = (mul_temp_1[63:32] != 32'b00000000000000000000000000000000 ? 32'b11111111111111111111111111111111 :
              mul_temp_1[31:0]);



endmodule  // Module_one1

