// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test\sample.v
// Created: 2020-12-14 11:44:27
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: sample
// Source Path: test/sample
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module sample
          (num_in,
           num_out);


  input   [7:0] num_in;  // uint8
  output  [7:0] num_out;  // uint8


  reg [7:0] num_out_1;  // uint8
  reg [7:0] eighth_digit;  // uint8
  reg [7:0] temp;  // ufix8
  reg [7:0] temp_0;  // ufix8
  reg [7:0] c;  // ufix8
  reg [7:0] c_0;  // ufix8
  reg signed [31:0] c_1;  // int32
  reg signed [31:0] t_0;  // int32


  always @(num_in) begin
    c_1 = 32'sd0;
    t_0 = 32'sd0;
    // ab = example of num, hex byte
    // get eighth digit
    temp = num_in;
    c = temp >>> 8'd7;
    eighth_digit = c;
    // left shift
    temp_0 = num_in;
    c_0 = temp_0 <<< 8'd1;
    num_out_1 = c_0;
    if (eighth_digit == 8'd1) begin
      //         B = hex2dec('1B'); % idk if that's fully right
      t_0 = {24'b0, c_0};
      c_1 = t_0 ^ 32'sd27;
      num_out_1 = c_1[7:0];
    end
  end



  assign num_out = num_out_1;

endmodule  // sample

