// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test\Subsystem.v
// Created: 2020-12-25 14:45:37
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem
// Source Path: test/Subsystem
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem
          (state,
           state1,
           state2,
           state3,
           state4,
           state5,
           state6,
           state7,
           state8,
           state9,
           state10,
           state11,
           state12,
           state13,
           state14,
           state15,
           temp_state,
           temp_state1,
           temp_state2,
           temp_state3,
           temp_state4,
           temp_state5,
           temp_state6,
           temp_state7,
           temp_state8,
           temp_state9,
           temp_state10,
           temp_state11,
           temp_state12,
           temp_state13,
           temp_state14,
           temp_state15,
           temp_state16,
           temp_state17,
           temp_state18,
           temp_state19,
           temp_state20,
           temp_state21,
           temp_state22,
           temp_state23,
           temp_state24,
           temp_state25,
           temp_state26,
           temp_state27,
           temp_state28,
           temp_state29,
           temp_state30,
           temp_state31,
           temp_state32,
           temp_state33,
           temp_state34,
           temp_state35,
           temp_state36,
           temp_state37,
           temp_state38,
           temp_state39,
           temp_state40,
           temp_state41,
           temp_state42,
           temp_state43);


  input   [7:0] state;  // uint8
  input   [7:0] state1;  // uint8
  input   [7:0] state2;  // uint8
  input   [7:0] state3;  // uint8
  input   [7:0] state4;  // uint8
  input   [7:0] state5;  // uint8
  input   [7:0] state6;  // uint8
  input   [7:0] state7;  // uint8
  input   [7:0] state8;  // uint8
  input   [7:0] state9;  // uint8
  input   [7:0] state10;  // uint8
  input   [7:0] state11;  // uint8
  input   [7:0] state12;  // uint8
  input   [7:0] state13;  // uint8
  input   [7:0] state14;  // uint8
  input   [7:0] state15;  // uint8
  output  [31:0] temp_state;  // uint32
  output  [31:0] temp_state1;  // uint32
  output  [31:0] temp_state2;  // uint32
  output  [31:0] temp_state3;  // uint32
  output  [31:0] temp_state4;  // uint32
  output  [31:0] temp_state5;  // uint32
  output  [31:0] temp_state6;  // uint32
  output  [31:0] temp_state7;  // uint32
  output  [31:0] temp_state8;  // uint32
  output  [31:0] temp_state9;  // uint32
  output  [31:0] temp_state10;  // uint32
  output  [31:0] temp_state11;  // uint32
  output  [31:0] temp_state12;  // uint32
  output  [31:0] temp_state13;  // uint32
  output  [31:0] temp_state14;  // uint32
  output  [31:0] temp_state15;  // uint32
  output  [31:0] temp_state16;  // uint32
  output  [31:0] temp_state17;  // uint32
  output  [31:0] temp_state18;  // uint32
  output  [31:0] temp_state19;  // uint32
  output  [31:0] temp_state20;  // uint32
  output  [31:0] temp_state21;  // uint32
  output  [31:0] temp_state22;  // uint32
  output  [31:0] temp_state23;  // uint32
  output  [31:0] temp_state24;  // uint32
  output  [31:0] temp_state25;  // uint32
  output  [31:0] temp_state26;  // uint32
  output  [31:0] temp_state27;  // uint32
  output  [31:0] temp_state28;  // uint32
  output  [31:0] temp_state29;  // uint32
  output  [31:0] temp_state30;  // uint32
  output  [31:0] temp_state31;  // uint32
  output  [31:0] temp_state32;  // uint32
  output  [31:0] temp_state33;  // uint32
  output  [31:0] temp_state34;  // uint32
  output  [31:0] temp_state35;  // uint32
  output  [31:0] temp_state36;  // uint32
  output  [31:0] temp_state37;  // uint32
  output  [31:0] temp_state38;  // uint32
  output  [31:0] temp_state39;  // uint32
  output  [31:0] temp_state40;  // uint32
  output  [31:0] temp_state41;  // uint32
  output  [31:0] temp_state42;  // uint32
  output  [31:0] temp_state43;  // uint32


  wire [31:0] w1;  // uint32
  wire [31:0] w2;  // uint32
  wire [31:0] w3;  // uint32
  wire [31:0] w4;  // uint32
  wire [31:0] w5;  // uint32
  wire [31:0] w6;  // uint32
  wire [31:0] w7;  // uint32
  wire [31:0] w8;  // uint32
  wire [31:0] w9;  // uint32
  wire [31:0] w10;  // uint32
  wire [31:0] w11;  // uint32
  wire [31:0] w12;  // uint32
  wire [31:0] w13;  // uint32
  wire [31:0] w14;  // uint32
  wire [31:0] w15;  // uint32
  wire [31:0] w16;  // uint32
  wire [31:0] w17;  // uint32
  wire [31:0] w18;  // uint32
  wire [31:0] w19;  // uint32
  wire [31:0] w20;  // uint32
  wire [31:0] w21;  // uint32
  wire [31:0] w22;  // uint32
  wire [31:0] w23;  // uint32
  wire [31:0] w24;  // uint32
  wire [31:0] w25;  // uint32
  wire [31:0] w26;  // uint32
  wire [31:0] w27;  // uint32
  wire [31:0] w28;  // uint32
  wire [31:0] w29;  // uint32
  wire [31:0] w30;  // uint32
  wire [31:0] w31;  // uint32
  wire [31:0] w32;  // uint32
  wire [31:0] w33;  // uint32
  wire [31:0] w34;  // uint32
  wire [31:0] w35;  // uint32
  wire [31:0] w36;  // uint32
  wire [31:0] w37;  // uint32
  wire [31:0] w38;  // uint32
  wire [31:0] w39;  // uint32
  wire [31:0] w40;  // uint32
  wire [31:0] w41;  // uint32
  wire [31:0] w42;  // uint32
  wire [31:0] w43;  // uint32
  wire [31:0] w44;  // uint32


  KeyExpansion u_KeyExpansion (.key1(state),  // uint8
                               .key2(state1),  // uint8
                               .key3(state2),  // uint8
                               .key4(state3),  // uint8
                               .key5(state4),  // uint8
                               .key6(state5),  // uint8
                               .key7(state6),  // uint8
                               .key8(state7),  // uint8
                               .key9(state8),  // uint8
                               .key10(state9),  // uint8
                               .key11(state10),  // uint8
                               .key12(state11),  // uint8
                               .key13(state12),  // uint8
                               .key14(state13),  // uint8
                               .key15(state14),  // uint8
                               .key16(state15),  // uint8
                               .w1(w1),  // uint32
                               .w2(w2),  // uint32
                               .w3(w3),  // uint32
                               .w4(w4),  // uint32
                               .w5(w5),  // uint32
                               .w6(w6),  // uint32
                               .w7(w7),  // uint32
                               .w8(w8),  // uint32
                               .w9(w9),  // uint32
                               .w10(w10),  // uint32
                               .w11(w11),  // uint32
                               .w12(w12),  // uint32
                               .w13(w13),  // uint32
                               .w14(w14),  // uint32
                               .w15(w15),  // uint32
                               .w16(w16),  // uint32
                               .w17(w17),  // uint32
                               .w18(w18),  // uint32
                               .w19(w19),  // uint32
                               .w20(w20),  // uint32
                               .w21(w21),  // uint32
                               .w22(w22),  // uint32
                               .w23(w23),  // uint32
                               .w24(w24),  // uint32
                               .w25(w25),  // uint32
                               .w26(w26),  // uint32
                               .w27(w27),  // uint32
                               .w28(w28),  // uint32
                               .w29(w29),  // uint32
                               .w30(w30),  // uint32
                               .w31(w31),  // uint32
                               .w32(w32),  // uint32
                               .w33(w33),  // uint32
                               .w34(w34),  // uint32
                               .w35(w35),  // uint32
                               .w36(w36),  // uint32
                               .w37(w37),  // uint32
                               .w38(w38),  // uint32
                               .w39(w39),  // uint32
                               .w40(w40),  // uint32
                               .w41(w41),  // uint32
                               .w42(w42),  // uint32
                               .w43(w43),  // uint32
                               .w44(w44)  // uint32
                               );

  assign temp_state = w1;

  assign temp_state1 = w2;

  assign temp_state2 = w3;

  assign temp_state3 = w4;

  assign temp_state4 = w5;

  assign temp_state5 = w6;

  assign temp_state6 = w7;

  assign temp_state7 = w8;

  assign temp_state8 = w9;

  assign temp_state9 = w10;

  assign temp_state10 = w11;

  assign temp_state11 = w12;

  assign temp_state12 = w13;

  assign temp_state13 = w14;

  assign temp_state14 = w15;

  assign temp_state15 = w16;

  assign temp_state16 = w17;

  assign temp_state17 = w18;

  assign temp_state18 = w19;

  assign temp_state19 = w20;

  assign temp_state20 = w21;

  assign temp_state21 = w22;

  assign temp_state22 = w23;

  assign temp_state23 = w24;

  assign temp_state24 = w25;

  assign temp_state25 = w26;

  assign temp_state26 = w27;

  assign temp_state27 = w28;

  assign temp_state28 = w29;

  assign temp_state29 = w30;

  assign temp_state30 = w31;

  assign temp_state31 = w32;

  assign temp_state32 = w33;

  assign temp_state33 = w34;

  assign temp_state34 = w35;

  assign temp_state35 = w36;

  assign temp_state36 = w37;

  assign temp_state37 = w38;

  assign temp_state38 = w39;

  assign temp_state39 = w40;

  assign temp_state40 = w41;

  assign temp_state41 = w42;

  assign temp_state42 = w43;

  assign temp_state43 = w44;

endmodule  // Subsystem

