// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test\test.v
// Created: 2020-12-14 11:44:27
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: test
// Source Path: test
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module test
          (num3,
           num4);


  input   [7:0] num3;  // uint8
  output  [7:0] num4;  // uint8


  wire [7:0] num_out;  // uint8


  sample u_sample (.num_in(num3),  // uint8
                   .num_out(num_out)  // uint8
                   );

  assign num4 = num_out;

endmodule  // test

