// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test\test.v
// Created: 2020-12-25 13:10:26
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: test
// Source Path: test
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module test;




  // All logic inside the DUT 'test' was detected to be redundant by HDL Coder. Consider connecting output ports to 
  // the design in order to preserve logic for code generation


endmodule  // test

